[pack]
icon = "pack.png"
modrinth_project_id = "FRSckbRo"

# Sodium
[[pack.modrinth_dependencies]]
project_id = "AANobbMI"
dependency_type = "optional"

[pack.name]
type = "text"
text = "Classic 3D"
color = "gold"
bold = true

[pack.description]
type = "text"
text = "Classic Minecraft look & feel with revamped 3D models"
color = "aqua"

[profile.debug]
output_type = "uncompressed"
relocation = "symbolic"
json_type = "pretty"

[profile.debug.pack.suffix]
type = "text"
text = " DEBUG"
color = "red"
bold = true

[profile.release]
output_type = "zip"
relocation = "symbolic"
json_type = "compact"
pack.license = "LICENSE.md"

[profile.release.pack.suffix]
type = "text"
text = " v2.0.0-A.10"
color = "red"

# 1.21.4

[build."1.21.4"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
    "1.20.3",
    "1.21.2",
    "1.21.4",
]
minecraft_versions = "1.21.4"
pack.format = 46

[build."1.21.4".pack.suffix]
type = "text"
text = " 1.21.4"
color = "yellow"

# 1.21.2

[build."1.21.2"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
    "1.20.3",
    "1.21.2",
]
minecraft_versions = ["1.21.2", "1.21.3"]
pack.format = 42

[build."1.21.2".pack.suffix]
type = "text"
text = " 1.21.2"
color = "yellow"

# 1.21

[build."1.21"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
    "1.20.3",
]
minecraft_versions = ["1.21", "1.21.1"]

[build."1.21".pack]
format.minimum = 33
format.maximum = 34

[build."1.21".pack.suffix]
type = "text"
text = " 1.21"
color = "yellow"

# 1.20

[build."1.20"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
    "1.20.3",
]
minecraft_versions = [
    "1.20",
    "1.20.1",
    "1.20.2",
    "1.20.3",
    "1.20.4",
    "1.20.5",
    "1.20.6",
]

[build."1.20".pack]
format.minimum = 15
format.maximum = 32

[build."1.20".pack.suffix]
type = "text"
text = " 1.20"
color = "yellow"

# 1.19

[build."1.19"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
]
minecraft_versions = ["1.19", "1.19.1", "1.19.2", "1.19.3", "1.19.4"]

[build."1.19".pack]
format = 13

[build."1.19".pack.suffix]
type = "text"
text = " 1.19"
color = "yellow"

# 1.18

[build."1.18"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.17",
]
minecraft_versions = ["1.18", "1.18.1", "1.18.2"]
pack.format = 8

[build."1.18".pack.suffix]
type = "text"
text = " 1.18"
color = "yellow"

# 1.18

[build."1.17"]
bundles = [
    "1.8",
    "1.9",
    "1.10",
    "1.13",
    "1.13-1.17.1",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.16-1.17.1",
    "1.17",
]
minecraft_versions = ["1.17", "1.17.1"]
pack.format = 7

[build."1.17".pack.suffix]
type = "text"
text = " 1.17"
color = "yellow"

# 1.16

[build."1.16"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.10",
    "1.13",
    "1.13-1.17.1",
    "1.14",
    "1.14-1.21.3",
    "1.16",
    "1.16-1.17.1",
]
minecraft_versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"]
pack.format = 6

[build."1.16".pack.suffix]
type = "text"
text = " 1.16"
color = "yellow"

# 1.15

[build."1.15"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.10",
    "1.13",
    "1.13-1.17.1",
    "1.14",
    "1.14-1.21.3",
    "1.13-1.15.2",
]
minecraft_versions = ["1.15", "1.15.1", "1.15.2"]
pack.format = 5

[build."1.15".pack.suffix]
type = "text"
text = " 1.15"
color = "yellow"

# 1.14

[build."1.14"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.10",
    "1.13",
    "1.13-1.17.1",
    "1.14",
    "1.14-1.21.3",
    "1.13-1.15.2",
]
minecraft_versions = ["1.14", "1.14.1", "1.14.2", "1.14.3", "1.14.4"]
pack.format = 4

[build."1.14".pack.suffix]
type = "text"
text = " 1.14"
color = "yellow"

# 1.13

[build."1.13"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.10",
    "1.13",
    "1.13-1.13.2",
    "1.13-1.17.1",
    "1.13-1.15.2",
]
minecraft_versions = ["1.13", "1.13.1", "1.13.2"]
pack.format = 4

[build."1.13".pack.suffix]
type = "text"
text = " 1.13"
color = "yellow"

# 1.12

[build."1.12"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.9-1.12.2",
    "1.10",
    "1.10-1.12.2",
    "-1.12.2",
]
minecraft_versions = ["1.12", "1.12.1", "1.12.2"]
pack.format = 3

[build."1.12".pack.suffix]
type = "text"
text = " 1.12"
color = "yellow"

# 1.11

[build."1.11"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.9-1.12.2",
    "1.10",
    "1.10-1.12.2",
    "-1.12.2",
]
minecraft_versions = ["1.11", "1.11.1", "1.11.2"]
pack.format = 3

[build."1.11".pack.suffix]
type = "text"
text = " 1.11"
color = "yellow"

# 1.10

[build."1.10"]
bundles = [
    "1.8",
    "1.9",
    "1.9-1.16.4",
    "1.9-1.12.2",
    "1.10",
    "1.10-1.12.2",
    "-1.12.2",
]
minecraft_versions = ["1.10", "1.10.1", "1.10.2"]
pack.format = 2

[build."1.10".pack.suffix]
type = "text"
text = " 1.10"
color = "yellow"

# 1.9

[build."1.9"]
bundles = ["1.8", "1.9", "1.9-1.16.4", "-1.9.4", "1.9-1.12.2", "-1.12.2"]
minecraft_versions = ["1.9", "1.9.1", "1.9.2", "1.9.3", "1.9.4"]
pack.format = 2

[build."1.9".pack.suffix]
type = "text"
text = " 1.9"
color = "yellow"
