[pack]
name = "Classic 3D"
description = "Adds more detail to Minecraft's models."

[pack.format]
minimum = 14
maximum = 31

[profile.debug]
output_type = "uncompressed"
relocation = "symbolic"
json_type = "pretty"

[profile.release]
output_type = "zip"
relocation = "copy"
json_type = "compact"

[build.1-20]
bundles = ["1.8", "1.13", "1.14", "1.16", "1.19", "1.19.3", "1.19.4"]
