[pack.name]
type = "text"
text = "Classic 3D"
color = "gold"
bold = true

[pack.description]
type = "text"
text = "Classic Minecraft look & feel with revamped 3D models"
color = "aqua"

[profile.debug]
output_type = "uncompressed"
relocation = "symbolic"
json_type = "pretty"

[profile.debug.pack.suffix]
type = "text"
text = " DEBUG"
color = "red"
bold = true

[profile.release]
output_type = "zip"
relocation = "symbolic"
json_type = "compact"

[profile.release.pack.suffix]
type = "text"
text = " v0.1.0A"
color = "red"

[build.1-20]
bundles = [
    "<=1.12.2->=1.19",
    "1.8",
    "1.9",
    "1.13",
    "1.14",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
]

[build.1-20.pack]
format.minimum = 14
format.maximum = 32

[build.1-20.pack.suffix]
type = "text"
text = " 1-20"
color = "yellow"

[build.1-19]
bundles = [
    "<=1.12.2->=1.19",
    "1.8",
    "1.9",
    "1.13",
    "1.14",
    "1.16",
    "1.17",
    "1.19",
    "1.19.3",
    "1.19.4",
]

[build.1-19.pack]
format = 13

[build.1-19.pack.suffix]
type = "text"
text = "1-19"
color = "yellow"
