[pack]
name = "Classic 3DR"
description = "Classic Minecraft textures but with more complex 3D models."

[profile.debug]
output_type = "uncompressed"
relocation = "symbolic"
json_type = "pretty"
pack.suffix = "[DEBUG]"

[profile.release]
output_type = "zip"
relocation = "copy"
json_type = "compact"

[build.1-20]
bundles = ["1.8", "1.13", "1.14", "1.16", "1.17", "1.19", "1.19.3", "1.19.4"]

[build.1-20.pack]
format.minimum = 14
format.maximum = 35
suffix = "1.20"
